/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp3_poo.view;

import java.awt.Color;
import java.awt.Component;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import tp3_poo.model.SujetExamen;
import tp3_poo.persistance.dao.SujetExamenDAO;

/**
 *
 * @author Moutek
 */
public class RechercherSujetExamenView extends javax.swing.JFrame {

    private List<SujetExamen> dataList;
    private final SujetExamenDAO dao;
    private final SujetExamenView sujetExamenView;

    /**
     * Creates new form RechercherSujetExamenView
     *
     * @param dao
     * @param sujetExamenView
     */
    public RechercherSujetExamenView(SujetExamenDAO dao, SujetExamenView sujetExamenView) {
        initComponents();
        setLocationRelativeTo(null);
        this.sujetExamenView = sujetExamenView;
        this.dao = dao;
        loadData();
    }

    private void loadData() {
        try {
            dataList = dao.lire();
            actualiser();
        } catch (Exception ex) {
            messageLabel.setText("Erreur lors du chargement des données; Raison : " + ex.getMessage());
            messageLabel.setForeground(Color.RED);
            messageLabel.setBackground(Color.WHITE);
            Logger.getLogger(RechercherSujetExamenView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void actualiser() {
        // On itère sur la liste des exercices du sujet examen
        int nbLignes = dataList.size();
        Object[][] data = new Object[nbLignes][9];
        int i = 0;
        for (SujetExamen se : dataList) {
            data[i][0] = se.getMatiere();
            data[i][1] = se.getAnnee();
            data[i][2] = se.getExercices().size();
            i++;
        }
        // Chaque exercice correspond à une ligne dans la table
        formTable.setModel(new DefaultTableModel(
                data,
                new String[]{
                    "Matière", "Année", "Nbre d'exos"
                }
        ));
        formTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    @Override
    public final void setLocationRelativeTo(Component c) {
        super.setLocationRelativeTo(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        formTable = new javax.swing.JTable();
        okButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();

        setTitle("Recherche de sujets d'examens");

        formTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matière", "Année", "Nbre d'exos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(formTable);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        messageLabel.setBackground(new java.awt.Color(255, 255, 255));
        messageLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton)
                .addGap(221, 221, 221))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(messageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // On prend en compte l'objet sélectionné
        // check for selected row first
        int s = formTable.getSelectedRow();
        if (s != -1) {
            // remove selected row from the view model
            sujetExamenView.setFormObject(dataList.get(s));
            setVisible(false);
        } else if (!dataList.isEmpty()) {
            messageLabel.setText("Sélectionnez un sujet svp...");
            messageLabel.setForeground(Color.CYAN);
            messageLabel.setBackground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_okButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable formTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
